### ISSUE TITLE
请问你python版本是多少

### ISSUE THREAD

**Issue by zjjgit** [PythonerKK/tornado-blog-restapi#1]
Traceback (most recent call last):
  File "/Users/jiajie/work/cym_env3/lib/python3.6/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
TypeError: object function can't be used in 'await' expression
我一直报这个错，认证走authenticated_async方法时

**Comment by jiangzuochen** [comment]
> Traceback (most recent call last):
> File "/Users/jiajie/work/cym_env3/lib/python3.6/site-packages/tornado/web.py", line 1699, in _execute
> result = await result
> TypeError: object function can't be used in 'await' expression
> 我一直报这个错，认证走authenticated_async方法时

==================================================================
Add bracket pair:() after every authenticated_async.
In other words,change every
`@authenticated_async
  async def get(self, *args, **kwargs):`
to
`@authenticated_async()
 async def get(self, *args, **kwargs):`

Reason：
Decorator with () will return coroutine object （Handler.get）while decorator  without () will return the function authenticated_async.<locals>.decorator.<locals>.wrapper.
